### ISSUE TITLE
a little addition to the mod?

### ISSUE THREAD

**Issue by okzerus** [OrangeBurrito/scenic#1]
hello! It's been more than a year since this mod was active in any way, but god I hope you're still doing fine and didn't quit minecraft's modding
this mod has one feature that I like so much - the treasure pots. and the fact that the loot from them can be configurable makes everything EVEN better.

I found out that treasure pots spawn not only in dungeons but on cobblestone blocks only. so I replaced some modded variations of stone and useless ores with cobblestone, and now my caves have treasure pots, literally as much as terraria have!
BUT, this version of scenic generates its blocks ONLY in overworld..
in my modpack, I have a lot of custom dimensions, and this is a big downside..

can you by any chance update this mod and make it generate its blocks in any dimension?.. I'm gonna say thanks a thousand times for this!

**Comment by OrangeBurrito** [comment]
Thanks for the comment, and I'll see if I can push a change soon.  It's about time I updated this to newer versions, with a revamped config (e.g. a dimension whitelist option)

**Comment by okzerus** [comment]
> Thanks for the comment, and I'll see if I can push a change soon. It's about time I updated this to newer versions, with a revamped config (e.g. a dimension whitelist option)

NOOO please tell me that dimension whitelist option will be for 1.16.5 as well
please don't stop supporting 1.16.5, this is the most popular and stable version for mods currently :(

**Comment by OrangeBurrito** [comment]
[Basic configuration](https://www.curseforge.com/minecraft/mc-mods/scenic-reforged/files/4419976) has now been implemented in 1.16.5 57f7feb9f0a328f58ec9e43b66fa756af5a77ea4
Please tell me if you encounter any issues/bugs in the new version.
